#!/bin/bash

# run_snapcraft: helper to run Snapcraft inside a container.

# replace the SNAPCRAFT_* tokens with the correct values for our Snapcraft image
sed --in-place='' "s/SNAPCRAFT_BASE/$SNAPCRAFT_BASE/" snap/snapcraft.yaml
sed --in-place='' "s/SNAPCRAFT_BUILD_BASE/$SNAPCRAFT_BUILD_BASE/" snap/snapcraft.yaml
docker run --rm -v `pwd`:/project snapcraft-rock:latest "$@"
